// <auto-generated />
using Biblioteca.Infraestructura.Datos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Biblioteca.Infraestructura.Datos.EF.Migrations
{
    [DbContext(typeof(BibliotecaContexto))]
    [Migration("20190430181022_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Biblioteca.Dominio.Entidades.Libro", b =>
                {
                    b.Property<int>("IDLibro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDEditorial");

                    b.Property<string>("ISBN");

                    b.Property<int>("NumeroPaginas");

                    b.Property<byte>("TipoLibro");

                    b.Property<string>("TituloLibro");

                    b.HasKey("IDLibro");

                    b.ToTable("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
